### ISSUE TITLE
Make notification on icon flexible

### ISSUE THREAD

**Issue by dinoslow** [Xiayucheng1212/buggy_extension#9]
![Screenshot 2024-04-01 at 01 23 19](https://github.com/Xiayucheng1212/buggy_extension/assets/73374146/44eaaf02-cf18-434e-a1ac-a0bd198ae692)
Currently, the draft number exceeding 3 digits will create an overflow on the notification mark. Make it stretch itself when the number gets larger.

**Comment by Xiayucheng1212** [comment]
Fixed
